### ISSUE TITLE
PXD006574

### ISSUE THREAD

**Issue by colin-combe** [Rappsilber-Laboratory/xiSPEC#16]
both the monomer and dimer datasets in PXD006574 produce an error when uploaded to spectrumviewer.org (by specifying the PRIDE accession) 

```
log id: qgvv1larr1j6tdd91ga3gnjqt3_1519211636.log (include this in the github issue)
error type: Error
message: list index out of range
id: undefined
```

https://www.ebi.ac.uk/pride/archive/projects/PXD006574

**Comment by lars-kolbowski** [comment]
found the problem:
the mzid uses the wrong cvTerm ''cross-link receiver' instead of "cross-link acceptor"
Probably best to change to check for MS:1002510 instead of the string or what do you think?

**Comment by colin-combe** [comment]
yes, checking for MS:1002510 probably better

**Comment by lars-kolbowski** [comment]
might be a bit more difficult/time consuming. Will talk to you about it tomorrow. Put in a temp fix for now. Files are now getting parsed but it seems like there are problems with the MGF 0/1 based index...
Also lot's of N-terminal cross-links in these files apparently. Their display in the FragKey could be improved I guess.

**Comment by colin-combe** [comment]
> there are problems with the MGF 0/1 based index...

Closing this issue as we no longer suffer from this misunderstanding about MGF files
